// 1対1対応に絞った問題集
// correct は choices 配列の正解インデックス（実行時にランダムシャッフルされる）
const QUESTIONS = [
  // ====== 辞書 ======
  {
    id: 'dict-keys', category: '辞書',
    question: '辞書からキーの一覧を取得するメソッドは？',
    choices: ['keys()', 'values()', 'items()', 'get()'],
    correct: 0,
    explanation: 'keys() がキー一覧、values() が値一覧、items() が (キー, 値) のタプル一覧。get() は単一キー検索。',
  },
  {
    id: 'dict-values', category: '辞書',
    question: '辞書から値の一覧を取得するメソッドは？',
    choices: ['values()', 'keys()', 'items()', 'pop()'],
    correct: 0,
    explanation: '値だけ欲しいときは values()。キーは keys()、両方は items()。',
  },
  {
    id: 'dict-items', category: '辞書',
    question: '辞書から (キー, 値) のタプル一覧を取得するメソッドは？',
    choices: ['items()', 'pairs()', 'entries()', 'tuples()'],
    correct: 0,
    explanation: 'items() が (k, v) を順に返す。「for k, v in d.items():」が定番。',
  },
  {
    id: 'dict-key-type', category: '辞書',
    question: '辞書のキーとして使えないのはどれ？',
    choices: ['list', 'tuple', 'str', 'int'],
    correct: 0,
    explanation: 'キーは hashable (immutable) でなければならない。list は変更可なので不可、tuple は不変なので可。',
  },
  {
    id: 'dict-empty', category: '辞書',
    question: '空の集合 (set) を作る正しい記法は？',
    choices: ['set()', '{}', '[]', '()'],
    correct: 0,
    explanation: '{} は空の辞書になる。空の集合は set() でしか作れない（{1, 2} のような中身があれば集合）。',
  },

  // ====== イテレーション ======
  {
    id: 'iter-zip', category: 'イテレーション',
    question: '2つのリストから同じ位置の要素をペアにする関数は？',
    choices: ['zip()', 'enumerate()', 'map()', 'pair()'],
    correct: 0,
    explanation: 'zip(a, b) で (a[0], b[0]), (a[1], b[1]) ... のイテレータを返す。enumerate は番号付け用。',
  },
  {
    id: 'iter-enum', category: 'イテレーション',
    question: 'リストの各要素に (インデックス, 要素) を付けて返す関数は？',
    choices: ['enumerate()', 'zip()', 'index()', 'list()'],
    correct: 0,
    explanation: 'enumerate(seq) は (0, seq[0]), (1, seq[1]) ... を返す。zip は別系列の結合用。',
  },
  {
    id: 'iter-zip-list', category: 'イテレーション',
    question: 'zip オブジェクトをリストに変換するには？',
    choices: ['list(zip(...))', 'zip(...).list()', 'tolist(zip(...))', 'zip.list(...)'],
    correct: 0,
    explanation: 'zip はイテレータを返すので、表示や添字アクセスには list() で変換する。',
  },
  {
    id: 'iter-unpack', category: 'イテレーション',
    question: 'リストの各要素を関数の位置引数として展開する記法は？',
    choices: ['func(*list)', 'func(**list)', 'func(list...)', 'func(...list)'],
    correct: 0,
    explanation: '* で位置引数アンパック、** で辞書をキーワード引数アンパック。print(*[1,2]) は print(1, 2) と同じ。',
  },

  // ====== 関数引数 ======
  {
    id: 'arg-args', category: '関数引数',
    question: '任意個の位置引数を受け取る記法は？',
    choices: ['*args', '**kwargs', 'args[]', '...args'],
    correct: 0,
    explanation: '*args が位置引数（タプルとして受け取る）、**kwargs がキーワード引数（辞書）。',
  },
  {
    id: 'arg-kwargs', category: '関数引数',
    question: '任意個のキーワード引数を受け取る記法は？',
    choices: ['**kwargs', '*args', 'kwargs={}', '@kwargs'],
    correct: 0,
    explanation: '**kwargs が辞書として受け取る。*args (タプル) より後ろに書く必要がある。',
  },
  {
    id: 'arg-order', category: '関数引数',
    question: '関数定義で *args と **kwargs を併用するとき、正しい順序は？',
    choices: ['*args が先', '**kwargs が先', 'どちらでも良い', '同時には書けない'],
    correct: 0,
    explanation: '位置引数 → *args → デフォルト引数 → **kwargs の順。**kwargs を先に書くと SyntaxError。',
  },
  {
    id: 'arg-default', category: '関数引数',
    question: '関数のデフォルト引数値が評価されるタイミングは？',
    choices: ['関数定義時に1回だけ', '呼び出しごとに毎回', 'モジュールロード時', 'インタープリタ起動時'],
    correct: 0,
    explanation: 'デフォルト値は定義時に評価され、関数オブジェクトに保持される。可変オブジェクト (list 等) を既定値にすると共有されて落とし穴になる。',
  },

  // ====== 標準ライブラリ ======
  {
    id: 'lib-dir', category: '標準ライブラリ',
    question: 'オブジェクトの属性・メソッド一覧を返す関数は？',
    choices: ['dir()', 'help()', 'list()', 'attrs()'],
    correct: 0,
    explanation: 'dir() は名前のリストを返す。使い方を説明するドキュメント表示は help()。',
  },
  {
    id: 'lib-help', category: '標準ライブラリ',
    question: 'オブジェクトのドキュメントを表示する関数は？',
    choices: ['help()', 'dir()', 'doc()', 'info()'],
    correct: 0,
    explanation: 'help(obj) でドキュメント表示。属性一覧は dir()。',
  },
  {
    id: 'lib-exit', category: '標準ライブラリ',
    question: 'プログラムを途中で終了させる関数は？',
    choices: ['sys.exit()', 'sys.quit()', 'sys.end()', 'sys.close()'],
    correct: 0,
    explanation: 'sys.exit() のみ正しい。quit/end/close は sys モジュールに存在しない。',
  },
  {
    id: 'lib-argv', category: '標準ライブラリ',
    question: 'コマンドライン引数を取得するリストは？',
    choices: ['sys.argv', 'sys.args', 'sys.argument', 'sys.cmdline'],
    correct: 0,
    explanation: 'sys.argv（args ではない）。argv[0] はスクリプト名、argv[1:] が引数。',
  },
  {
    id: 'lib-smtplib', category: '標準ライブラリ',
    question: 'メールを送信する標準モジュールは？',
    choices: ['smtplib', 'poplib', 'imaplib', 'mailto'],
    correct: 0,
    explanation: 'smtplib が送信。受信は poplib (POP3) や imaplib (IMAP)。',
  },
  {
    id: 'lib-poplib', category: '標準ライブラリ',
    question: 'POP3 でメールを受信する標準モジュールは？',
    choices: ['poplib', 'smtplib', 'recvmail', 'mailbox'],
    correct: 0,
    explanation: 'poplib が POP3 受信。送信は smtplib、IMAP は imaplib。',
  },
  {
    id: 'lib-pack', category: '標準ライブラリ',
    question: 'struct モジュールで Python の値をバイナリに変換する関数は？',
    choices: ['pack()', 'unpack()', 'encode()', 'binary()'],
    correct: 0,
    explanation: 'pack が Python→バイナリ、unpack がバイナリ→Python。方向に注意。',
  },
  {
    id: 'lib-unpack', category: '標準ライブラリ',
    question: 'struct モジュールでバイナリを Python の値に戻す関数は？',
    choices: ['unpack()', 'pack()', 'decode()', 'parse()'],
    correct: 0,
    explanation: 'unpack がバイナリ→Python、pack が Python→バイナリ。',
  },
  {
    id: 'lib-rand-choice', category: '標準ライブラリ',
    question: 'random モジュールでシーケンスから1つランダムに選ぶ関数は？',
    choices: ['random.choice()', 'random.sample()', 'random.pick()', 'random.random()'],
    correct: 0,
    explanation: 'choice() は1つ。sample(seq, n) は n 個（重複なし）、random() は 0.0〜1.0 未満の小数。',
  },
  {
    id: 'lib-rand-sample', category: '標準ライブラリ',
    question: 'random モジュールでシーケンスから重複なく複数選ぶ関数は？',
    choices: ['random.sample()', 'random.choice()', 'random.choices()', 'random.multi()'],
    correct: 0,
    explanation: 'sample(seq, n) は重複なし。choices(seq, k=n) は重複あり。',
  },
  {
    id: 'lib-rand-random', category: '標準ライブラリ',
    question: 'random.random() の戻り値の範囲は？',
    choices: ['0.0以上1.0未満の浮動小数', '-1.0以上1.0以下の浮動小数', '0以上1以下の整数', '0以上指定値未満の整数'],
    correct: 0,
    explanation: '[0.0, 1.0) の浮動小数点数。範囲指定整数は randrange() / randint()。',
  },
  {
    id: 'lib-logging', category: '標準ライブラリ',
    question: 'logging モジュールのログレベルを深刻度の低い順に並べたものは？',
    choices: [
      'DEBUG → INFO → WARNING → ERROR → CRITICAL',
      'INFO → DEBUG → WARNING → ERROR → CRITICAL',
      'DEBUG → WARNING → INFO → ERROR → CRITICAL',
      'INFO → WARNING → DEBUG → ERROR → CRITICAL',
    ],
    correct: 0,
    explanation: 'DEBUG (詳細) → INFO (通常) → WARNING (警告) → ERROR (機能不全) → CRITICAL (致命的)。',
  },
  {
    id: 'lib-timeit', category: '標準ライブラリ',
    question: 'コードの実行時間を計測するモジュールは？',
    choices: ['timeit', 'doctest', 'unittest', 'time.clock'],
    correct: 0,
    explanation: 'timeit が実行時間計測。doctest は docstring 内のテスト、unittest はユニットテストフレームワーク。',
  },

  // ====== パッケージ管理 ======
  {
    id: 'pkg-freeze', category: 'パッケージ',
    question: 'インストール済みパッケージを requirements.txt に出力するコマンドは？',
    choices: [
      'pip freeze > requirements.txt',
      'pip export > requirements.txt',
      'pip dump > requirements.txt',
      'pip save > requirements.txt',
    ],
    correct: 0,
    explanation: 'pip freeze で「name==version」形式の出力。export/dump/save は存在しない。',
  },
  {
    id: 'pkg-upgrade', category: 'パッケージ',
    question: 'インストール済みパッケージを最新版に更新するコマンドは？',
    choices: [
      'pip install --upgrade パッケージ名',
      'pip install パッケージ名',
      'pip update パッケージ名',
      'pip refresh パッケージ名',
    ],
    correct: 0,
    explanation: '--upgrade (-U) なしで再インストールしても更新されない。pip update は存在しない。',
  },
  {
    id: 'pkg-install-r', category: 'パッケージ',
    question: 'requirements.txt から一括インストールするコマンドは？',
    choices: [
      'pip install -r requirements.txt',
      'pip install requirements.txt',
      'pip restore requirements.txt',
      'pip freeze < requirements.txt',
    ],
    correct: 0,
    explanation: '-r (--requirement) フラグでファイル指定。',
  },

  // ====== 構文 / モジュール ======
  {
    id: 'syn-fromimport', category: '構文',
    question: 'モジュール内の関数を全てインポートする正しい構文は？',
    choices: [
      'from モジュール import *',
      'import モジュール from *',
      'import * from モジュール',
      'include モジュール',
    ],
    correct: 0,
    explanation: 'from X import Y の形が基本。逆順は SyntaxError。「_」始まりはインポートされない。',
  },
  {
    id: 'syn-self', category: '構文',
    question: 'メソッド定義の第1引数として慣習的に使う名前は？',
    choices: ['self', 'this', 'cls', 'me'],
    correct: 0,
    explanation: 'self が慣習。第1引数なしで定義するとインスタンス経由の呼び出しでエラー。クラスメソッドは cls。',
  },
  {
    id: 'syn-tuple1', category: '構文',
    question: '1要素のタプルを作るのに必須なのは？',
    choices: ['末尾のカンマ ("a",)', '丸括弧で囲む ("a")', '型注釈', 'バッククォート'],
    correct: 0,
    explanation: 'カンマで識別される。("a") は単なる文字列、("a",) はタプル。1要素時は括弧があってもカンマが必須。',
  },
  {
    id: 'syn-triple', category: '構文',
    question: '改行を含む文字列リテラルを作るには？',
    choices: [
      'トリプルクォート """ または \'\'\'',
      'シングルクォートで複数行',
      'バックスラッシュで継続',
      'バッククォート',
    ],
    correct: 0,
    explanation: '"""..."""  または \'\'\'...\'\'\' で複数行可。普通のクォートで素直に改行は SyntaxError。',
  },
  {
    id: 'syn-implicit', category: '構文',
    question: '隣接する文字列リテラル ("a" "b") の結果は？',
    choices: ['"ab" に連結される', '"a b" になる', 'タプル ("a", "b")', 'SyntaxError'],
    correct: 0,
    explanation: '空白で隣接した文字列リテラルは + なしで連結される（コンパイル時）。変数同士では機能しない。',
  },
  {
    id: 'syn-nonlocal', category: '構文',
    question: 'ネストした関数で、1つ外側のローカル変数を書き換える宣言は？',
    choices: ['nonlocal', 'global', 'outer', 'parent'],
    correct: 0,
    explanation: 'nonlocal は1つ外側のスコープ、global はモジュール全体（最外）の変数を指す。',
  },
  {
    id: 'syn-lambda', category: '構文',
    question: 'リスト内のタプル要素の2番目で並べ替えるラムダ式は？',
    choices: [
      'key=lambda x: x[1]',
      'key=lambda x: x[0]',
      'key=lambda x: x.second',
      'key=x[1]',
    ],
    correct: 0,
    explanation: 'sort(key=...) の key には1引数の関数を渡す。lambda x: x[インデックス] が定番イディオム。',
  },

  // ====== データ型 ======
  {
    id: 'type-mutable', category: 'データ型',
    question: 'mutable（変更可能）なデータ型はどれ？',
    choices: ['list', 'tuple', 'str', 'int'],
    correct: 0,
    explanation: 'list / dict / set が mutable。tuple / str / int / float / frozenset は immutable。',
  },
  {
    id: 'type-append', category: 'データ型',
    question: 'リスト末尾に1要素を追加するメソッドは？',
    choices: ['append()', 'extend()', 'add()', 'insert()'],
    correct: 0,
    explanation: 'append(x) は1要素を追加。extend(iter) は別シーケンスの全要素をバラして追加。',
  },
  {
    id: 'type-extend', category: 'データ型',
    question: 'リストに別シーケンスの全要素を追加するメソッドは？',
    choices: ['extend()', 'append()', 'concat()', 'merge()'],
    correct: 0,
    explanation: 'extend([1,2]) → 末尾に 1, 2 を別々に追加。append([1,2]) はリストごと1要素として追加。',
  },
  {
    id: 'type-sort', category: 'データ型',
    question: 'リスト自身をソートし、None を返すメソッドは？',
    choices: ['list.sort()', 'sorted(list)', 'list.order()', 'list.arrange()'],
    correct: 0,
    explanation: 'sort() は破壊的・None を返す。sorted() は非破壊・新しいリストを返す。',
  },
  {
    id: 'type-sorted', category: 'データ型',
    question: '元のリストを変更せず、ソート済みの新しいリストを返すのは？',
    choices: ['sorted(list)', 'list.sort()', 'list.sorted()', 'sort(list)'],
    correct: 0,
    explanation: 'sorted() は組み込み関数で新リスト返却。sort() はメソッドで破壊的。',
  },

  // ====== 正規表現 ======
  {
    id: 'regex-star', category: '正規表現',
    question: '正規表現で「直前の文字を 0 回以上繰り返す」を表す記号は？',
    choices: ['*', '+', '?', '#'],
    correct: 0,
    explanation: '* は 0+ 回（無くてもマッチ）、+ は 1+ 回（必ず1回はある）、? は 0 または 1 回。',
  },
  {
    id: 'regex-plus', category: '正規表現',
    question: '正規表現で「直前の文字を 1 回以上繰り返す」を表す記号は？',
    choices: ['+', '*', '?', '!'],
    correct: 0,
    explanation: '+ は 1+ 回（必ず1回は必要）。* は 0+ 回（無くても可）。? は 0 または 1 回。',
  },
  {
    id: 'regex-question', category: '正規表現',
    question: '正規表現で「直前の文字が 0 回または 1 回」を表す記号は？',
    choices: ['?', '*', '+', '@'],
    correct: 0,
    explanation: '? は 0 か 1 回。* は 0+ 回、+ は 1+ 回。',
  },
  {
    id: 'regex-boundary', category: '正規表現',
    question: '正規表現で「単語境界」を表すのは？',
    choices: ['\\b', '\\w', '\\s', '\\B'],
    correct: 0,
    explanation: '\\b が境界、\\w が英数字、\\s が空白、\\B は境界以外。',
  },
  {
    id: 'regex-digit', category: '正規表現',
    question: '正規表現で「数字 1 文字」を表すのは？',
    choices: ['\\d', '\\w', '\\D', '\\s'],
    correct: 0,
    explanation: '\\d は数字、\\D は数字以外、\\w は英数字（数字含む）、\\s は空白。',
  },

  // ====== PEP8 ======
  {
    id: 'pep-class', category: 'PEP8',
    question: 'PEP8 でクラス名に推奨される命名規則は？',
    choices: ['UpperCamelCase', 'lower_case_with_underscores', 'lowerCamelCase', 'UPPER_CASE'],
    correct: 0,
    explanation: 'クラスは UpperCamelCase（PascalCase）。関数・変数は snake_case、定数は UPPER_CASE。',
  },
  {
    id: 'pep-func', category: 'PEP8',
    question: 'PEP8 で関数名・変数名に推奨される命名規則は？',
    choices: ['lower_case_with_underscores', 'UpperCamelCase', 'lowerCamelCase', 'UPPER_CASE'],
    correct: 0,
    explanation: '関数・変数は snake_case (lower_case_with_underscores)。クラスは UpperCamelCase。',
  },

  // ====== インタープリタ ======
  {
    id: 'int-interp', category: 'インタープリタ',
    question: 'インタープリタ言語の特徴として正しいのは？',
    choices: [
      '1行ずつ翻訳しながら実行',
      'プログラム全体を一括で機械語に翻訳してから実行',
      '実行に exe 化が必須',
      'OS ごとにコンパイルが必要',
    ],
    correct: 0,
    explanation: '一括翻訳はコンパイル言語の特徴。Python はインタープリタ言語で 1 行ずつ実行。',
  },
  {
    id: 'int-history', category: 'インタープリタ',
    question: '対話モードのヒストリ（履歴）が保存されるデフォルトファイルは？',
    choices: ['.python_history', '__history__.py', 'history.log', '.bash_history'],
    correct: 0,
    explanation: 'ホームディレクトリの .python_history に保存される（先頭ドット）。',
  },
  {
    id: 'int-tab', category: 'インタープリタ',
    question: '対話モードで補完機能を呼び出すキーは？',
    choices: ['Tab', 'Tab+C', 'Ctrl+Space', 'Enter'],
    correct: 0,
    explanation: '[Tab] のみ。複数候補があれば再度 [Tab] で切り替え。',
  },
  {
    id: 'int-operator', category: 'インタープリタ',
    question: '演算子そのもの（+, -, * など）の呼称は？',
    choices: ['オペレーター', 'オペランド', 'オペレーション', 'パラメータ'],
    correct: 0,
    explanation: '演算子＝オペレーター、演算対象（値や変数）＝オペランド。逆に覚えやすいので注意。',
  },
  {
    id: 'int-operand', category: 'インタープリタ',
    question: '演算対象の値や変数（a + b の a, b）の呼称は？',
    choices: ['オペランド', 'オペレーター', 'パラメータ', 'アーギュメント'],
    correct: 0,
    explanation: 'オペランド＝対象。オペレーター＝記号。パラメータ／引数は関数の話。',
  },
  {
    id: 'int-c-option', category: 'インタープリタ',
    question: 'コマンドラインから直接 Python コードを実行するオプションは？',
    choices: ['python -c "code"', 'python -e "code"', 'python --run "code"', 'python -x "code"'],
    correct: 0,
    explanation: '-c オプションで直接コード実行。-i はスクリプト実行後に対話モードへ入る。',
  },

  // ====== 例外 ======
  {
    id: 'exc-order', category: '例外',
    question: 'try-except-else-finally の正しい順序は？',
    choices: [
      'try → except → else → finally',
      'try → else → except → finally',
      'try → finally → except → else',
      'try → except → finally → else',
    ],
    correct: 0,
    explanation: 'else は except の後、finally が最後。else は try が例外なく終わったときに実行される。',
  },
  {
    id: 'exc-flow', category: '例外',
    question: '例外がキャッチされたとき、try 節の残りの処理はどうなる？',
    choices: [
      '実行されず except へジャンプ',
      '例外を投げた行以外は全て実行される',
      '例外発生後も try 節は最後まで実行される',
      'プログラム全体が終了する',
    ],
    correct: 0,
    explanation: '例外発生で try の残りはスキップされ、対応する except へ。',
  },
  {
    id: 'exc-multiple', category: '例外',
    question: '単一の except 節で複数の例外をキャッチする正しい書き方は？',
    choices: [
      'except (TypeError, ValueError):',
      'except TypeError, ValueError:',
      'except TypeError | ValueError:',
      'except [TypeError, ValueError]:',
    ],
    correct: 0,
    explanation: 'タプルで指定: except (A, B):。Python 2 のカンマ区切りは現行不可。',
  },
  {
    id: 'exc-raise', category: '例外',
    question: '意図的に例外を発生させる文は？',
    choices: [
      'raise ValueError("msg")',
      'throw ValueError("msg")',
      'except ValueError',
      'error ValueError',
    ],
    correct: 0,
    explanation: 'Python は raise（throw ではない）。raise 例外クラス(メッセージ) または raise 例外クラス。',
  },
  {
    id: 'exc-finally', category: '例外',
    question: 'finally 節が実行されるのはいつ？',
    choices: [
      '例外発生の有無にかかわらず必ず最後に実行',
      '例外が発生したときだけ',
      '例外が発生しなかったときだけ',
      'except 節がない場合のみ',
    ],
    correct: 0,
    explanation: 'finally は必ず実行される（クリーンアップ用途）。return/break/continue があっても直前に実行される。',
  },
];
